# Generated by Django 4.2.23 on 2025-06-13 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code_oaci', models.CharField(max_length=4)),
                ('frequence_radio_mhz', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodrome.ad')),
            ],
        ),
        migrations.CreateModel(
            name='Pistes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=7)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodrome.ad')),
            ],
        ),
        migrations.CreateModel(
            name='Carburants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodrome.ad')),
            ],
        ),
        migrations.CreateModel(
            name='Batiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodrome.ad')),
            ],
        ),
        migrations.CreateModel(
            name='Aprons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodrome.ad')),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodrome.batiments')),
            ],
        ),
    ]
