# Generated by Django 4.2.23 on 2025-06-17 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icao_code', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='RadioFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_mhz', models.FloatField()),
            ],
            options={
                'ordering': ['frequency_mhz'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('service_type', models.CharField(choices=[('MAINTENANCE_STATION', 'Maintenance Station'), ('AD_INFO', 'AD Info'), ('ATC', 'ATC'), ('NOTAM', 'NOTAM')], default='MAINTENANCE_STATION', max_length=50)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='aerodrome.ad')),
            ],
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=7)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runways', to='aerodrome.ad')),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('MOGAS_98', 'MoGas 98'), ('AVGAS_100LL', 'Avgas 100LL'), ('JET_A1', 'Jet A-1')], default='MOGAS_98', max_length=20)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuels', to='aerodrome.ad')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('building_type', models.CharField(choices=[('HANGAR', 'Hangar'), ('MAINTENANCE', 'Maintenance'), ('CONTROL_TOWER', 'Control Tower'), ('SECURITY_OFFICE', 'Security Office'), ('GAS_STATION', 'Gas Station')], default='HANGAR', max_length=50)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='aerodrome.ad')),
            ],
        ),
        migrations.CreateModel(
            name='Apron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('apron_type', models.CharField(choices=[('GENERAL_AVIATION', 'General Aviation Apron'), ('TRAINING', 'Training Apron'), ('HELICOPTER', 'Helicopter Apron'), ('MAINTENANCE', 'Maintenance Apron')], default='GENERAL_AVIATION', max_length=100)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprons', to='aerodrome.ad')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprons', to='aerodrome.building')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='frequencies',
            field=models.ManyToManyField(to='aerodrome.radiofrequency'),
        ),
    ]
