# Generated by Django 4.2.23 on 2025-06-17 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerodrome', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aprons',
            new_name='Apron',
        ),
        migrations.RenameModel(
            old_name='Batiments',
            new_name='Building',
        ),
        migrations.RenameModel(
            old_name='Carburants',
            new_name='Fuel',
        ),
        migrations.RenameModel(
            old_name='Pistes',
            new_name='Runway',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='frequence_radio_mhz',
            new_name='frequency_mhz',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='code_oaci',
            new_name='icao_code',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='apron',
            old_name='batiment',
            new_name='building',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='nom',
            new_name='name',
        ),
    ]
