# Generated by Django 4.2.23 on 2025-06-17 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aerodrome', '0002_rename_aprons_apron_rename_batiments_building_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apron',
            old_name='type',
            new_name='apron_type',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='type',
            new_name='building_type',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='type',
            new_name='service_type',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='type',
        ),
        migrations.AddField(
            model_name='fuel',
            name='fuel_type',
            field=models.CharField(choices=[('MOGAS_98', 'MoGas 98'), ('AVGAS_100LL', 'Avgas 100LL'), ('JET_A1', 'Jet A-1')], default='JET_A1', max_length=20),
        ),
        migrations.AlterField(
            model_name='apron',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprons', to='aerodrome.ad'),
        ),
        migrations.AlterField(
            model_name='apron',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprons', to='aerodrome.building'),
        ),
        migrations.AlterField(
            model_name='building',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='aerodrome.ad'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuels', to='aerodrome.ad'),
        ),
        migrations.AlterField(
            model_name='runway',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runways', to='aerodrome.ad'),
        ),
        migrations.AlterField(
            model_name='service',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='aerodrome.ad'),
        ),
    ]
